# testing Pod life cycle
apiVersion: v1
kind: Pod
metadata:
  name: hello-world
  labels:
    app: web
spec:
  containers:
    - name: web-ctr
      image: nigelpoulton/getting-started-k8s:1.0
      ports:
        - containerPort: 8080
